--------------------------------------------------------------------------------
-- Amazon Prime
--------------------------------------------------------------------------------
INSERT INTO STREAMING_SERVICE(ID, NAME) VALUES (1, 'Amazon Prime Video');

-- (1) Star Trek: Picard
INSERT INTO SERIES(
    STREAMING_SERVICE_ID, NAME, IMDB_ID,
    COUNTRY, YEAR_FROM, YEAR_TO, MAX_SEASONS, IN_PRODUCTION,
    DESCRIPTION
) VALUES(
    1, 'Star Trek: Picard', 'tt8806524',
    'USA', 2020, 2020, 1, true,
    'Star Trek: Picard zeigt wie Sir Patrick Stewart seine berühmte Rolle als Jean-Luc Picard wiederaufnimmt, den er sieben Staffeln lang bei Raumschiff Enterprise - Das nächste Jahrhundert verkörperte. Die neue Serie begleitet die Kultfigur auf ihrem nächsten Lebensabschnitt.'
);

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, NAME, IMDB_ID) VALUES(1, 1, 1, 'Gedenken', 'tt9381924');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, NAME, IMDB_ID) VALUES(1, 1, 2, 'Karten und Legenden', 'tt9420276');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, NAME, IMDB_ID) VALUES(1, 1, 3, 'Das Ende ist der Anfang', 'tt9420278');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, NAME, IMDB_ID) VALUES(1, 1, 4, 'Unbedingte Offenheit', 'tt9420280');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, NAME, IMDB_ID) VALUES(1, 1, 5, 'Keine Gnade', 'tt9420282');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, NAME, IMDB_ID) VALUES(1, 1, 6, 'Die geheimnisvolle Box', 'tt9420284');

-- (2) Akte X
INSERT INTO SERIES(
    STREAMING_SERVICE_ID, NAME, IMDB_ID,
    COUNTRY, YEAR_FROM, YEAR_TO, MAX_SEASONS, IN_PRODUCTION,
    DESCRIPTION
) VALUES(
    1, 'Akte X: Die unheimlichen Fälle des FBI', 'tt0106179',
    'USA', 1993, 2018, 8, false,
    'Seit Fox Mulder als kleiner Junge miterleben musste, wie seine Schwester Samantha scheinbar von Außerirdischen entführt wurde, glaubt er an deren Existenz und paranormale Phänomene.'
);

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1,  1, 'tt0170817', 'Gezeichnet');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1,  2, 'tt0751099', 'Die Warnung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1,  3, 'tt0751208', 'Das Nest');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1,  4, 'tt0751094', 'Signale');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1,  5, 'tt0751229', 'Der Teufel von Jersey');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1,  6, 'tt0751201', 'Schatten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1,  7, 'tt0751131', 'Die Maschine');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1,  8, 'tt0751141', 'Eis');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1,  9, 'tt0751207', 'Besessen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 10, 'tt0751120', 'Gefallener Engel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 11, 'tt0751116', 'Eve');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 12, 'tt0751124', 'Feuer');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 13, 'tt0751083', 'Die Botschaft');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 14, 'tt0751129', 'Verlockungen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 15, 'tt0751152', 'Lazarus');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 16, 'tt0751265', 'Ewige Jugend');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 17, 'tt0751108', 'Täuschungsmanöver');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 18, 'tt0751162', 'Der Wunderheiler');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 19, 'tt0751202', 'Verwandlungen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 20, 'tt0751097', 'Der Kokon');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 21, 'tt0751246', 'Ein neues Nest');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 22, 'tt0751086', 'Wiedergeboren');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 23, 'tt0751193', 'Roland');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 1, 24, 'tt0751224', 'Das Labor');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2,  1, 'tt0751154', 'Kontakt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2,  2, 'tt0751228', 'Der Parasit');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2,  3, 'tt0751085', 'Blut');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2,  4, 'tt0751204', 'Schlaflos');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2,  5, 'tt0751107', 'Unter Kontrolle – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2,  6, 'tt0751077', 'Seilbahn zu den Sternen – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2,  7, 'tt0751066', 'Drei');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2,  8, 'tt0751169', 'An der Grenze');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2,  9, 'tt0751125', 'Der Vulkan');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 10, 'tt0751185', 'Rotes Museum');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 11, 'tt0751117', 'Excelsis Dei');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 12, 'tt0751078', 'Böse geboren');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 13, 'tt0751144', 'Todestrieb');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 14, 'tt0751102', 'Satan');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 15, 'tt0751128', 'Frische Knochen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 16, 'tt0751093', 'Die Kolonie – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 17, 'tt0751114', 'Die Kolonie – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 18, 'tt0751121', 'Sophie');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 19, 'tt0751103', 'Totenstille');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 20, 'tt0751139', 'Der Zirkus');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 21, 'tt0751222', 'Heilige Asche');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 22, 'tt0751119', 'Verseucht');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 23, 'tt0751206', 'Das Experiment');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 24, 'tt0751173', 'Unsere kleine Stadt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 2, 25, 'tt0751074', 'Anasazi – Teil 1');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3,  1, 'tt0751221', 'Das Ritual – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3,  2, 'tt0751174', 'Verschwörung des Schweigens – Teil 3');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3,  3, 'tt0751095', 'Blitzschlag');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3,  4, 'tt0751092', 'Der Hellseher');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3,  5, 'tt0751230', 'Die Liste');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3,  6, 'tt0751065', 'Fett');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3,  7, 'tt0751240', 'Der zweite Körper');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3,  8, 'tt0751172', 'Parallele');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3,  9, 'tt0751166', 'Die Autopsie – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 10, 'tt0751068', 'Der Zug – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 11, 'tt0751191', 'Offenbarung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 12, 'tt0751259', 'Kreig der Koprophagen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 13, 'tt0751212', 'Energie');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 14, 'tt0751132', 'Groteske');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 15, 'tt0751180', 'Der Feind – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 16, 'tt0751075', 'Der Feind – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 17, 'tt0751183', 'Mein Wille sei dein Wille');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 18, 'tt0751218', 'Der Fluch');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 19, 'tt0751133', 'Höllengeld');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 20, 'tt0751147', 'Andere Wahrheiten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 21, 'tt0751080', 'Heimsuchung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 22, 'tt0751184', 'Der See');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 23, 'tt0751260', 'Ferngesteuert');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 3, 24, 'tt0751213', 'Der Tag steht schon fest – Teil 1');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4,  1, 'tt0751135', 'Herrenvolk – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4,  2, 'tt0751137', 'Blutschande');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4,  3, 'tt0751214', 'Teliko');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4,  4, 'tt0751255', 'Unruhe');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4,  5, 'tt0751225', 'Rückkehr der Seelen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4,  6, 'tt0751197', 'Hexensabbat');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4,  7, 'tt0751164', 'Gedanken des geheimnisvollen Rauchers');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4,  8, 'tt0751251', 'Tunguska – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4,  9, 'tt0751216', 'Tunguska – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 10, 'tt0751175', 'Die Sammlung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 11, 'tt0751109', 'Der Chupacabra');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 12, 'tt0751153', 'Leonard Betts');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 13, 'tt0751165', 'Mutterkorn');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 14, 'tt0751158', 'Memento Mori');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 15, 'tt0751149', 'Der Golem');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 16, 'tt0751254', 'Unsichtbar');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 17, 'tt0751215', 'Tempus Fugit – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 18, 'tt0751156', 'Tempus Fugit – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 19, 'tt0751211', 'Rückkehr aus der Zukunft');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 20, 'tt0751205', 'Ein unbedeutender Niemand');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 21, 'tt0751266', 'Der Pakt mit dem Teufel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 22, 'tt0751110', 'Todes-Omen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 23, 'tt0751100', 'Dämonen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 4, 24, 'tt0751130', 'Gethsemane');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5,  1, 'tt0751187', 'Redux – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5,  2, 'tt0751188', 'Redux – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5,  3, 'tt0751256', 'Die unüblichen Verdächtigen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5,  4, 'tt0751101', 'Vom Erdboden verschluckt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5,  5, 'tt0751232', 'Der große Mutato');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5,  6, 'tt0751090', 'Emily – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5,  7, 'tt0751111', 'Emily – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5,  8, 'tt0751151', 'Kitsunegari');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5,  9, 'tt0751199', 'Die Wurzeln des Bösen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 10, 'tt0751089', 'Ein Spiel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 11, 'tt0751150', 'Kill Switch');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 12, 'tt0751081', 'Böses Blut');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 13, 'tt0751177', 'Cassandra – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 14, 'tt0751234', 'Cassandra – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 15, 'tt0751247', 'Gute Patrioten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 16, 'tt0751161', 'Das innere Auge');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 17, 'tt0751070', 'Alle Seelen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 18, 'tt0751231', 'Die Pine-Bluff-Variante');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 19, 'tt0751127', 'Folie à Deux');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 5, 20, 'tt0751223', 'Das Ende');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6,  1, 'tt0751220', 'Der Anfang');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6,  2, 'tt0751106', 'Die Fahrt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6,  3, 'tt0751249', 'Im Bermuda-Dreieck');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6,  4, 'tt0751104', 'Dreamland – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6,  5, 'tt0751105', 'Dreamland – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6,  6, 'tt0751138', 'Die Geister, die ich rief');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6,  7, 'tt0751217', 'Zeit der Zärtlichkeit');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6,  8, 'tt0751233', 'Der Regenmacher');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6,  9, 'tt0751195', 'S.R. 819');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 10, 'tt0751245', 'Tithonus');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 11, 'tt0751252', 'Zwei Väter – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 12, 'tt0751170', 'Ein Sohn – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 13, 'tt0751069', 'Aqua Mala');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 14, 'tt0751163', 'Montag');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 15, 'tt0751076', 'Arkadien');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 16, 'tt0751073', 'Alpha');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 17, 'tt0751248', 'Trevor');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 18, 'tt0751159', 'Milargo');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 19, 'tt0751239', 'Ex');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 20, 'tt0751244', 'Suzanne');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 21, 'tt0751122', 'Sporen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 6, 22, 'tt0419384', 'Artefakte');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7,  1, 'tt0751235', 'Böse Zeichen – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7,  2, 'tt0751236', 'Tausend Stimmen – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7,  3, 'tt0751140', 'Hunger');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7,  4, 'tt0751160', 'Millennium');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7,  5, 'tt0751194', 'Masse mal Beschleunigung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7,  6, 'tt0751227', 'Das Glück des Henry Weems');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7,  7, 'tt0751171', 'Tor zur Hölle');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7,  8, 'tt0751219', 'Der unglaubliche Maleeni');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7,  9, 'tt0751203', 'Schlangen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 10, 'tt0751200', 'Alte Seelen – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 11, 'tt0751091', 'Sternenlicht – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 12, 'tt0751264', 'Vollmond');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 13, 'tt0751126', 'Game Over');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 14, 'tt0751241', 'Zauberstaub');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 15, 'tt0751113', 'Cobra');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 16, 'tt0751088', 'Zerbrochene Spiegel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 17, 'tt0751071', 'Augenblicke');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 18, 'tt0751087', 'Nikotin');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 19, 'tt0751136', 'Hollywood');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 20, 'tt0751123', '27.000.000 : 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 21, 'tt0751145', 'Drei Wünsche');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 7, 22, 'tt0751190', 'Alles beginnt in Oregon – Teil 1');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8,  1, 'tt0751262', 'Verschwunden – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8,  2, 'tt0751263', 'Gibson Praise – Teil 3');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8,  3, 'tt0751176', 'Klauen und Zähne');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8,  4, 'tt0751192', 'Gesteinigt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8,  5, 'tt0751143', 'Billy');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8,  6, 'tt0751186', 'Rückwärts');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8,  7, 'tt0751257', 'Via Negativa');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8,  8, 'tt0751210', 'Fenster der Seele');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8,  9, 'tt0751196', 'Schlaues Metall');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 10, 'tt0751082', 'Hier und nicht hier');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 11, 'tt0751226', 'Der Seelenesser');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 12, 'tt0751157', 'Underground');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 13, 'tt0751178', 'Frucht des Leibes');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 14, 'tt0751242', 'Es ist zu spät – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 15, 'tt0751098', 'Lebendig tot – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 16, 'tt0751243', 'Drei Worte');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 17, 'tt0751112', 'Feuer und Asche');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 18, 'tt0751258', 'Sie kommen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 19, 'tt0751072', 'Augenlicht');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 20, 'tt0751115', 'Einer von vielen – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 8, 21, 'tt0751118', 'William – Teil 2');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9,  1, 'tt0751167', 'Unter Wasser – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9,  2, 'tt0751168', 'Adam und Eva – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9,  3, 'tt0751096', 'Daemonicus');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9,  4, 'tt0751067', '4-D');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9,  5, 'tt0751155', 'Der Herr der Fliegen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9,  6, 'tt0751250', 'Schattenmann');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9,  7, 'tt0751146', 'Desaparecido');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9,  8, 'tt0751134', 'Häutungen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9,  9, 'tt0751181', 'Drohungen – Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9, 10, 'tt0751182', 'Die Prophezeiung – Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9, 11, 'tt0751079', 'Audrey');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9, 12, 'tt0751253', 'Der Mörder in mir');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9, 13, 'tt0751142', 'Sechs und neun');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9, 14, 'tt0751198', 'Unter dem Bett');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9, 15, 'tt0751148', 'Helden');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9, 16, 'tt0751261', 'Zum Wohle des Kindes');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9, 17, 'tt0751189', 'Erlösung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9, 18, 'tt0751209', 'Die perfekte Familie');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 9, 19, 'tt0408347', 'Die Wahrheit');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 10,  1, 'tt4549938', 'Der Kampf');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 10,  2, 'tt4549948', 'Gründer-Mutation');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 10,  3, 'tt4549942', 'Mulder und Scully gegen das Wer-Monster');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 10,  4, 'tt4549940', 'Heimat');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 10,  5, 'tt4549946', 'Babylon');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 10,  6, 'tt4549954', 'Der Kampf II');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 11,  1, 'tt6803156', 'Der Kampf III');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 11,  2, 'tt6803224', 'Dieses Leben, jenes Leben');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 11,  3, 'tt6803102', 'Galgenmännchen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 11,  4, 'tt6803158', 'Der Mandela-Effekt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 11,  5, 'tt6803126', 'Ghouli');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 11,  6, 'tt6803232', 'Kätzchen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 11,  7, 'tt6803124', 'Rm9sbG93ZXJz');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 11,  8, 'tt6803236', 'Das Tor zur Hölle');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 11,  9, 'tt6803176', 'Nichts währt ewig');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(2, 11, 10, 'tt6803128', 'Der Kampf IV');

-- (3) Knight Rider
INSERT INTO SERIES(
    STREAMING_SERVICE_ID, NAME, IMDB_ID,
    COUNTRY, YEAR_FROM, YEAR_TO, MAX_SEASONS, IN_PRODUCTION,
    DESCRIPTION
) VALUES(
    1, 'Knight Rider', 'tt0083437',
    'USA', 1982, 1986, 4, false,
    '"Knight Rider" war die Kultserie der 80-er Jahre: Wenn der ehemalige Polizist Michael Knight mit seinem Wunderauto K.I.T.T. (Knight Industries Two Thousand) im Auftrag der Foundation für Recht und Verfassung auf Verbrecherjagd ging, schlugen weltweit die Herzen der nicht nur jungen Fans höher.'
);

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1,  1, 'tt0084218', 'Michael Knight/Wie alles begann (Teil 1)');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1,  2, 'tt2388039', 'Michael Knight/Wie alles begann (Teil 2)');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1,  3, 'tt0620811', 'Tödliche Manöver');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1,  4, 'tt0620820', 'Der Bandenkrieg');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1,  5, 'tt0620871', 'Sammys Sensationsshow');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1,  6, 'tt0620826', 'Minister auf Abwegen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1,  7, 'tt0620862', 'Die große Dürre');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1,  8, 'tt0620860', 'Ein Richter spielt sein Spiel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1,  9, 'tt0620882', 'Der Doppelgänger');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 10, 'tt0620824', 'Gangster wider Willen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 11, 'tt0620875', 'Das endgültige Urteil');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 12, 'tt0620799', 'Das Gipfeltreffen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 13, 'tt0620813', 'Zwischen zwei Frauen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 14, 'tt0620822', 'Herzen aus Stein');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 15, 'tt0620815', 'Ein mysteriöser Saboteur');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 16, 'tt0620880', 'Geheimcode Topaz');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 17, 'tt0620798', 'Eine Musterstadt ohne Verbrechen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 18, 'tt0620805', 'Die Helios-Nadel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 19, 'tt0620884', 'Weißer Vogel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 20, 'tt0620834', 'Unerwünschte Konkurrenz');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 21, 'tt0620861', 'Computerspiele');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 1, 22, 'tt0620868', 'Gekidnappt');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2,  1, 'tt0620818', 'Goliath Teil I: Goliaths Geburt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2,  2, 'tt2643950', 'Goliath Teil II: Der Kampf mit Goliath');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2,  3, 'tt0620802', 'Der Erpresser');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2,  4, 'tt0620857', 'Händler des Todes');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2,  5, 'tt0620801', 'Blindes Vertrauen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2,  6, 'tt0620866', 'Geheimversteck Cadiz');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2,  7, 'tt0620827', 'Der Fassadenkletterer');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2,  8, 'tt0620807', 'Devon Miles in Nöten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2,  9, 'tt0620872', 'K.I.T.T. sitzt in der Falle');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 10, 'tt0620867', 'Ein Ring aus Feuer');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 11, 'tt0620852', 'Gedächtnisschwund');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 12, 'tt0620869', 'Eine schöne Bescherung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 13, 'tt0620797', 'Die Schatzsuche');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 14, 'tt0620812', 'Diamantenschmuggel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 15, 'tt0620885', 'Eine Kleinstadt lebt gefährlich');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 16, 'tt0620864', 'Wettlauf mit dem Tod');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 17, 'tt0620873', 'Goliath kommt zurück');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 19, 'tt0620816', 'Schnelle Teufel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 20, 'tt0620796', 'Gefährliches Spielzeug');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 21, 'tt0620858', 'Goldschmuggel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 23, 'tt0620854', 'Ich werde ewig dein Freund bleiben');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 2, 24, 'tt0620800', 'Einer spielt falsch');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3,  1, 'tt0620844', 'Ein geheimnisvoller Roboter (I)');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3,  3, 'tt0620876', 'Das zweite Gesicht');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3,  4, 'tt0620853', 'Fahrerflucht');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3,  5, 'tt0620821', 'Tödliches Kostümfest');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3,  6, 'tt0620828', 'Der schwarze Teufel taucht wieder auf');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3,  7, 'tt0620878', 'Viehdiebe – Der gemeine Apfel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3,  8, 'tt0620840', 'Michael fällt in Ungnade');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3,  9, 'tt0620809', 'Tödliche Orchideen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 10, 'tt0620855', 'K.I.T.T. kriegt einen Schlag');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 11, 'tt0620843', 'Das Chamäleon');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 12, 'tt0620808', 'Mord nach Maß');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 13, 'tt0620839', 'Eine Nasenlänge voraus');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 14, 'tt0620825', 'Eine schreckliche Falle');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 15, 'tt0620804', 'Der Konkurs');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 16, 'tt0620851', 'Ein Neubau mit Wanzen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 17, 'tt0620877', 'Das 19. Loch');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 18, 'tt0620831', 'Elliot, der Schlaukopf');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 19, 'tt0620874', 'Shattners Komplott');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 20, 'tt0620841', 'Michael Knight und die Zuflucht');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 21, 'tt0620838', 'Die Waffenbörse');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 3, 22, 'tt0620806', 'Der Tod unter der Zirkuskuppel');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4,  1, 'tt0620846', 'K.I.T.T.s Unfall mit Folgen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4,  3, 'tt0620829', 'Kidnapping');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4,  4, 'tt0620870', 'Die Flugzeugentführung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4,  5, 'tt0620803', 'Die heilige Grabstätte');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4,  6, 'tt0620881', 'Aus Spaß wird bitterer Ernst');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4,  7, 'tt0620837', 'Tödliche Bakterien');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4,  8, 'tt0620856', 'Herzlichen Glückwunsch');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4,  9, 'tt0620835', 'Der Tod fährt mit');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 10, 'tt0620832', 'Knight hinter Gittern');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 11, 'tt0620836', 'Die Bodenspekulanten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 12, 'tt0620879', 'Duft einer Rose');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 13, 'tt0620830', 'Killer K.I.T.T.');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 14, 'tt0620863', 'Wie die Axt im Walde');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 15, 'tt0620810', 'Zauberspiele');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 16, 'tt0620865', 'Die Boxmeisterschaft');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 17, 'tt0620842', 'Wer anderen eine Grube gräbt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 18, 'tt0620823', 'Der Brandstifter');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 19, 'tt0620833', 'Der Militärputsch');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 20, 'tt0620814', 'Der unheimliche Mönch');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 21, 'tt0620850', 'K.I.T.T.s Unfall mit Folgen (I)');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(3, 4, 22, 'tt0620883', 'K.I.T.T.s Unfall mit Folgen (II)');

-- (4) ALF
INSERT INTO SERIES(
    STREAMING_SERVICE_ID, NAME, IMDB_ID,
    COUNTRY, YEAR_FROM, YEAR_TO, MAX_SEASONS, IN_PRODUCTION,
    DESCRIPTION
) VALUES(
   1, 'ALF', 'tt0090390',
    'USA', 1986, 1990, 4, false,
    'Der Außerirdische ALF wird nach einer Notlandung auf der Erde von der Familie Tanner aufgenommen. Deren Leben bringt das zottelige Wesen mit dem trockenen Humor und der Vorliebe für Katzen von nun an gehörig durcheinander. ALF löste in den 80er Jahren eine wahre Hysterie aus.'
);

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1,  1, 'tt0822953', 'Hallo, da bin ich');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1,  2, 'tt0768299', 'Die Nacht, in der die Pizza kam');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1,  3, 'tt0504444', 'Katzenjammer');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1,  4, 'tt0504421', 'Großer Mann, was nun?');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1,  5, 'tt0504430', 'Parasit mit Puderquaste');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1,  6, 'tt0504416', 'Ganz im Vertrauen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1,  7, 'tt0504399', 'Ein Mädchen namens Rhonda');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1,  8, 'tt0504405', 'Eifersucht nach Noten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1,  9, 'tt0504397', 'Der Sprung in die Tiefe');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 10, 'tt0504415', 'Die Spritztour');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 11, 'tt0768300', 'Fröhliche Ferie');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 12, 'tt0504429', 'Eine schöne Bescherung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 13, 'tt0768309', 'Wenn Schwiegermutter kommt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 14, 'tt0504425', 'Die Fernsehfamilie');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 15, 'tt0504386', 'Mit den besten Wünschen aus dem Jenseits');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 16, 'tt0504412', 'Gestatten, mein Name ist Schlegel - Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 17, 'tt0504454', 'Gestatten, mein Name ist Schlegel - Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 18, 'tt0504455', 'Der Ausreißer');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 19, 'tt0504392', 'Ein Käfig für den Narren');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 20, 'tt0768312', 'Der Rollentausch');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 21, 'tt0504401', 'Das Fenster zum Garten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 22, 'tt0504420', 'Bühne frei für Spargelspitzen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 23, 'tt0504413', 'Schulden und Sühne');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 24, 'tt0504449', 'Brians Sternstunde');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 25, 'tt0504463', 'Der Kammerjäger und die Kakerlake');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 1, 26, 'tt0504417', 'Der blinde Passagier');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2,  1, 'tt0768656', 'Stets zu ihren Diensten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2,  2, 'tt0504439', 'Reif für die Insel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2,  3, 'tt0504447', 'Ein Schock fürs Leben');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2,  4, 'tt0504462', 'In der Kutte des Büßers');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2,  5, 'tt0504431', 'Zur besten Sendezeit');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2,  6, 'tt0504435', 'Das Kostümfest');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2,  7, 'tt0504428', 'Der Schönheitswettbewerb');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2,  8, 'tt0504438', 'Schluckauf Marke Melmac');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2,  9, 'tt0504427', 'Eine Reise durch die Nacht');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 10, 'tt0768306', 'Paradies für Flitterwöchner');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 11, 'tt0504402', 'Der Traumkandidat');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 12, 'tt0504387', 'Wenn der Weihnachtsmann kommt - Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 13, 'tt0504388', 'Wenn der Weihnachtsmann kommt - Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 14, 'tt0768310', 'Der Junge von nebenan');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 15, 'tt0768650', 'Anwalt in eigener Sache');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 16, 'tt0504461', 'Onkel Albert');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 17, 'tt0504436', 'Auf Verbrecherjagd - Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 18, 'tt0504437', 'Auf Verbrecherjagd - Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 19, 'tt0768654', 'Die Untermieterin');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 20, 'tt0504465', 'Ein Widersacher auf vier Beinen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 21, 'tt0504407', 'Auge um Auge');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 22, 'tt0504426', 'Die Beförderung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 23, 'tt0504411', 'Paules Puppenspieler');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 24, 'tt0504448', 'Der Geist aus der Flasche');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 25, 'tt0504460', 'Der Schritt in die Öffentlichkeit');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 2, 26, 'tt0504458', 'Nebenjob gesucht');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3,  1, 'tt0504443', 'Rendezvous gefälligst');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3,  2, 'tt0504440', 'Blick zurück nach vorn');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3,  3, 'tt0768649', 'Nachbarschaftshilfe');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3,  4, 'tt0504450', 'Tonight, Tonight - Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3,  5, 'tt0504451', 'Tonight, Tonight - Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3,  6, 'tt0504432', 'Reden ist Blech');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3,  7, 'tt0504456', 'Der mysteriöse Fremde - Teil 1');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3,  8, 'tt0504457', 'Der mysteriöse Fremde - Teil 2');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3,  9, 'tt0504394', 'Auf neuen Wegen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 10, 'tt0768308', 'Ein Hippie namens Willie');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 11, 'tt0504389', 'Cousin Blinky');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 12, 'tt0768651', 'Der Zauberlehrling');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 13, 'tt0504406', 'Der Zeuge im Netz');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 14, 'tt0504398', 'Ein Fall für drei');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 15, 'tt0504446', 'Ich und der King');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 16, 'tt0504390', 'Ein Baby auf Probe');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 17, 'tt0504433', 'Erpresser am Telefon');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 18, 'tt0504441', 'Der Liebesdiener');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 19, 'tt0504445', 'Der Pechvogel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 20, 'tt0504452', 'Zwischen zwei Stühlen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 21, 'tt0768652', 'Der Herr der Ameisen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 22, 'tt0768301', 'Bangemachen gilt nicht');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 23, 'tt0504404', 'Mutter Langfinger');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 24, 'tt0768653', 'Der Tramp');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 25, 'tt0504434', 'Die Erde bebt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 3, 26, 'tt0768304', 'Der Geburtshelfer');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4,  1, 'tt0504391', 'Eric, wo bist du?');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4,  2, 'tt0504418', 'Mr. Universum');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4,  3, 'tt0504459', 'Der Heiratsschwindler');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4,  4, 'tt0768655', 'Wie gewonnen, so zerronnen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4,  5, 'tt0504424', 'Ein Seelenkundler für den Hausgebrauch');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4,  6, 'tt0504408', 'Im Baumwollrausch');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4,  7, 'tt0768305', 'Bruder Neal');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4,  8, 'tt0768311', 'Darf ich bekannt machen...');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4,  9, 'tt0504419', 'Alles für die Katz');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 10, 'tt0504393', 'Ungebetene Gäste');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 11, 'tt0504403', 'Männerwirtschaft');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 12, 'tt0768302', 'Ein schwieriger Patient');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 13, 'tt0504414', 'Die Hawaii-Party');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 14, 'tt0504423', 'Es war einmal ein Komiker');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 15, 'tt0504422', 'In letzter Minute');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 16, 'tt0504453', 'Genie und Wahnsinn');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 17, 'tt0768303', 'Der Jodelpriester');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 18, 'tt0504400', 'Blendende Aussichten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 19, 'tt0504464', 'Die Seniorenparty');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 20, 'tt0768307', 'Auf Schatzsuche');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 21, 'tt0504442', 'Der Umweltschützer');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 22, 'tt0504409', 'Die Wolfshungerdiät');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 23, 'tt0504410', 'Umzugsfreuden');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(4, 4, 24, 'tt0504396', 'Die Entscheidung');


--------------------------------------------------------------------------------
-- Netflix
--------------------------------------------------------------------------------
INSERT INTO STREAMING_SERVICE(ID, NAME) VALUES (2, 'Netflix');

-- (5) Star Trek: Discovery
INSERT INTO SERIES(
    STREAMING_SERVICE_ID, NAME, IMDB_ID,
    COUNTRY, YEAR_FROM, YEAR_TO, MAX_SEASONS, IN_PRODUCTION,
    DESCRIPTION
) VALUES(
    2, 'Star Trek: Discovery', 'tt5171438',
    'USA', 2017, 2019, 2, true,
    'Zehn Jahre vor Kirk, Spock und der Enterprise entdeckt die USS Discovery neue Welten und Lebensformen, als ein Sternenflottenoffizier alle fremden Dinge verstehen lernt.'
);

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1,  1, 'tt5509372', 'Leuchtfeuer');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1,  2, 'tt5835712', 'Das Urteil');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1,  3, 'tt5835714', 'Lakaien und Könige');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1,  4, 'tt5870994', 'Sprung');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1,  5, 'tt5870996', 'Wähle deinen Schmerz');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1,  6, 'tt5870998', 'Lethe');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1,  7, 'tt5884346', 'T=Mudd²');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1,  8, 'tt5888594', 'Si Vis Pacem, Para Bellum');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1,  9, 'tt5890578', 'Algorithmus');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1, 10, 'tt6011050', 'Nur wegen dir');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1, 11, 'tt6011052', 'Der Wolf im Inneren');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1, 12, 'tt6011054', 'Blindes Verlangen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1, 13, 'tt6011058', 'Auftakt zur Vergangenheit');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1, 14, 'tt6902342', 'Flucht nach vorn');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 1, 15, 'tt6902346', 'Nimm meine Hand');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2,  1, 'tt7562000', 'Bruder');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2,  2, 'tt8282868', 'New Eden');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2,  3, 'tt8288432', 'Lichtpunkt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2,  4, 'tt8201650', 'Charonspfennig');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2,  5, 'tt8288434', 'Alte Bekannte');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2,  6, 'tt8288436', 'Donnerhall');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2,  7, 'tt8288438', 'Licht und Schatten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2,  8, 'tt8288440', 'Soweit die Erinnerung reicht');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2,  9, 'tt8288444', 'Projekt Daedalus');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2, 10, 'tt8282872', 'Der rote Engel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2, 11, 'tt8288442', 'Der Zeitsturm');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2, 12, 'tt8288446', 'Tal der Schatten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2, 13, 'tt8288448', 'Solch süße Traue');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(5, 2, 14, 'tt9572608', 'Süße Trauer, Teil 2');

-- (6) Travelers: Die Reisenden
INSERT INTO SERIES(
    STREAMING_SERVICE_ID, NAME, IMDB_ID,
    COUNTRY, YEAR_FROM, YEAR_TO, MAX_SEASONS, IN_PRODUCTION,
    DESCRIPTION
) VALUES(
    2, 'Travelers: Die Reisenden', 'tt5651844',
    'USA', 2016, 2018, 3, false,
    'In Hunderten von Jahren entdecken die überlebenden Menschen, wie sie das Bewusstsein durch die Zeit zurück in die Menschen des 21. Jahrhunderts schicken können, während sie versuchen, den Weg der Menschheit zu ändern.'
);

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1,  1, 'tt5696852', 'Pilot');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1,  2, 'tt5812500', 'Protokoll 6');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1,  3, 'tt5669708', 'Aleksander');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1,  4, 'tt5812512', 'Hall');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1,  5, 'tt5821948', 'Zimmer 101');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1,  6, 'tt5789060', 'Helios 685');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1,  7, 'tt5810528', 'Protokoll 5');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1,  8, 'tt5801288', 'Donner');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1,  9, 'tt5812534', 'Bishop');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1, 10, 'tt5812538', 'Kathryn');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1, 11, 'tt5812546', 'Marcy');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 1, 12, 'tt5838524', 'Grace');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2,  1, 'tt6718710', 'Ave Machina');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2,  2, 'tt6750210', 'Protokoll 4');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2,  3, 'tt6750220', 'Jacob');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2,  4, 'tt6750222', '11:27');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2,  5, 'tt6931938', 'Jenny');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2,  6, 'tt6931942', 'U235');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2,  7, 'tt6750224', '17 Minuten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2,  8, 'tt6931944', 'Reisender 0027');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2,  9, 'tt6931950', 'Update');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2, 10, 'tt7146890', '21C');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2, 11, 'tt7057604', 'Simon');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 2, 12, 'tt7167388', '001');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 3,  1, 'tt8153470', 'Ilsa');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 3,  2, 'tt8354802', 'Yates');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 3,  3, 'tt8557174', 'Protokoll 3');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 3,  4, 'tt8366864', 'Perrow');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 3,  5, 'tt8907834', 'Naomi');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 3,  6, 'tt8879460', 'Philip');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 3,  7, 'tt9035606', 'Trevor');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 3,  8, 'tt9035614', 'Archiv');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 3,  9, 'tt9035620', 'David');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(6, 3, 10, 'tt9035624', 'Protokoll Omega');

-- (7) Stranger Things
INSERT INTO SERIES(
    STREAMING_SERVICE_ID, NAME, IMDB_ID,
    COUNTRY, YEAR_FROM, YEAR_TO, MAX_SEASONS, IN_PRODUCTION,
    DESCRIPTION
) VALUES(
    2, 'Stranger Things', 'tt4574334',
    'USA', 2016, 2019, 3, true,
    'Wenn ein kleiner Junge verschwindet, müssen seine Mutter, ein Polizeichef und seine Freunde sich erschreckenden übernatürlichen Kräften stellen, um ihn zurückzuholen. '
);

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 1,  1, 'tt4593118', 'Kapitel eins: Das Verschwinden des Will Byers');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 1,  2, 'tt4593122', 'Kapitel zwei: Die Verrückte auf der Maple Street');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 1,  3, 'tt4593126', 'Kapitel drei: Grausame Nacht');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 1,  4, 'tt4593124', 'Kapitel vier: Die Leiche');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 1,  5, 'tt4593128', 'Kapitel fünf: Der Floh und der Akrobat');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 1,  6, 'tt4593132', 'Kapitel sechs: Das Monster');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 1,  7, 'tt4593134', 'Kapitel sieben: Die Badewanne');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 1,  8, 'tt4593138', 'Kapitel acht: Die andere Seite');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 2,  1, 'tt6020684', 'Kapitel eins: MAD MAX');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 2,  2, 'tt6020792', 'Kapitel zwei: Süßes oder Saures, Freak');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 2,  3, 'tt6020796', 'Kapitel drei: Die Kaulquappe');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 2,  4, 'tt6020802', 'Kapitel vier: Will, der Weise');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 2,  5, 'tt6020806', 'Kapitel fünf: Dig Dug');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 2,  6, 'tt6020808', 'Kapitel sechs: Der Spion');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 2,  7, 'tt6020810', 'Kapitel sieben: Die verlorene Schwester');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 2,  8, 'tt6020812', 'Kapitel acht: Der Gedankenschinder');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 2,  9, 'tt6020876', 'Kapitel neun: Das Tor');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 3,  1, 'tt7445494', 'Kapitel eins: Suzie, hörst du mich? ');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 3,  2, 'tt7640050', 'Kapitel zwei: Ratten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 3,  3, 'tt7911866', 'Kapitel drei: Die verschwundene Rettungsschwimmerin');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 3,  4, 'tt7911884', 'Kapitel vier: Der Sauna-Test');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 3,  5, 'tt7911894', 'Kapitel fünf: Die Armee');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 3,  6, 'tt7911914', 'Kapitel sechs: E Pluribus Unum');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 3,  7, 'tt7911930', 'Kapitel sieben: Der Biss');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(7, 3,  8, 'tt7911942', 'Kapitel acht: Die Schlacht von Starcourt');

-- (8) Dark
INSERT INTO SERIES(
    STREAMING_SERVICE_ID, NAME, IMDB_ID,
    COUNTRY, YEAR_FROM, YEAR_TO, MAX_SEASONS, IN_PRODUCTION,
    DESCRIPTION
) VALUES(
    2, 'Dark', 'tt5753856',
    'Deutschland', 2017, 2019, 2, true,
    'Eine Familiensaga mit einer übernatürlichen Wendung, die in einer deutschen Stadt spielt, in der das Verschwinden von zwei kleinen Kindern die Beziehungen zwischen vier Familien aufdeckt.'
);

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 1,  1,  'tt6305578', 'Geheimnisse');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 1,  2,  'tt7305776', 'Lügen');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 1,  3,  'tt7305820', 'Gestern und Heute');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 1,  4,  'tt7305818', 'Doppelleben');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 1,  5,  'tt7313308', 'Wahrheiten');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 1,  6,  'tt7313312', 'Sic mundus creatus est');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 1,  7,  'tt7305824', 'Kreuzwege');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 1,  8,  'tt7313316', 'Was man sät, das wird man ernten 	');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 1,  9,  'tt7313320', 'Alles ist jetzt');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 1,  10, 'tt7313322', 'Alpha und Omega');

INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 2,  1, 'tt7787482', 'Anfänge und Enden');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 2,  2, 'tt10454716', 'Dunkle Materie');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 2,  3, 'tt10454722', 'Gespenster');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 2,  4, 'tt10454726', 'Die Reisenden');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 2,  5, 'tt10454732', 'Vom Suchen und Finden');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 2,  6, 'tt10454734', 'Ein unendlicher Kreis');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 2,  7, 'tt10457652', 'Der weiße Teufel');
INSERT INTO EPISODE(SERIES_ID, SEASON, NUMBER, IMDB_ID, NAME) VALUES(8, 2,  8, 'tt10457654', 'Enden und Anfänge');
